SELECT
    h.HISTORY_ID,
    ROUND (
    CASE
        -- 대여 기록 별로 fee 계산
        -- 대여기간: 7일 미만
        WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 < 7
        THEN (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * c.DAILY_FEE
        -- 대여기간: 7 ~ 29
        WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 BETWEEN 7 AND 29
        THEN (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * c.DAILY_FEE * (1 - dp1.DISCOUNT_RATE / 100)
        -- 대여기간: 30 ~ 89
        WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 BETWEEN 30 AND 89
        THEN (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * c.DAILY_FEE * (1 - dp2.DISCOUNT_RATE / 100)
        ELSE
            (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * c.DAILY_FEE * (1 - dp3.DISCOUNT_RATE / 100)
    END) -- round
        AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY h USING(CAR_ID)
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp1 ON c.CAR_TYPE = dp1.CAR_TYPE AND dp1.DURATION_TYPE = '7일 이상'
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp2 ON c.CAR_TYPE = dp2.CAR_TYPE AND dp2.DURATION_TYPE = '30일 이상'
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp3 ON c.CAR_TYPE = dp3.CAR_TYPE AND dp3.DURATION_TYPE = '90일 이상'
WHERE
    c.CAR_TYPE = '트럭'
GROUP BY
    h.HISTORY_ID
ORDER BY
    FEE DESC, HISTORY_ID DESC;