SELECT
    CAR_ID,
    CAR_TYPE,
    DAILY_FEE,
    OPTIONS
FROM CAR_RENTAL_COMPANY_CAR
-- WHERE OPTIONS IN '네비게이션'  -- 틀린 답안
WHERE OPTIONS REGEXP '네비게이션'-- 정규표현식 REGEXP 사용
-- WHERE OPTIONS LIKE '%네비게이션%'-- LIKE 사용
ORDER BY CAR_ID DESC;