SELECT
    YEAR(s.SALES_DATE) AS YEAR,
    MONTH(s.SALES_DATE) AS MONTH,
    COUNT(DISTINCT u.USER_ID) AS PUCHASED_USERS,
    ROUND((
        COUNT(DISTINCT u.USER_ID) /
        (
            SELECT COUNT(USER_ID)
            FROM USER_INFO
            WHERE YEAR(JOINED) = 2021
        )
    ), 1)
    AS PUCHASED_RATIO
FROM USER_INFO u
JOIN ONLINE_SALE s USING(USER_ID)
WHERE YEAR(u.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH