

-- JOIN 을 사용하여, 세 테이블을 결합하고, GROUP BY 절을 사용하여, 저자별. 카테고리별로 매출앱을 '집계'한 뒤, 결과를 정렬.

SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS SALES
FROM
    BOOK B
JOIN
    AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN
    BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE
    S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY
    A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY
    A.AUTHOR_ID ASC, B.CATEGORY DESC;