
-- Solution 1
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;


-- Solution 2
SELECT
    i.FOOD_TYPE, i.REST_ID, i.REST_NAME, i.FAVORITES
FROM REST_INFO i
INNER JOIN (
    SELECT
        FOOD_TYPE, MAX(FAVORITES) AS maxFavorites
    FROM
        REST_INFO
    GROUP BY
        FOOD_TYPE
) AS max_f ON i.FOOD_TYPE = max_f.FOOD_TYPE AND i.FAVORITES = max_f.maxFavorites
ORDER BY FOOD_TYPE DESC;


-- 오답 판정
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE
HAVING MAX(FAVORITES)
ORDER BY FOOD_TYPE DESC;

-- 오답 2
SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES)
FROM REST_INFO
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;


/*
SELECT 문에 있는 모든 열은 집계 함수가 되거나 GROUP BY 절에 나타나야 합니다. 
GROUP BY 절을 사용하는데 만약 SELECT 문에 집계 함수를 사용하지 않거나 
GROUP BY 절에 언급되지 않은 열이 존재한다면 오류가 발생합니다. 

*/